/**
 * Google OAuth2 authentication helpers.
 *
 * Uses the OAuth2Client from google-auth-library (already a project
 * dependency for the Google Sheets JWT auth) to drive the server-side
 * OAuth2 code flow.
 *
 * Required environment variables:
 *   GOOGLE_OAUTH_CLIENT_ID      – OAuth2 web-app client ID
 *   GOOGLE_OAUTH_CLIENT_SECRET  – OAuth2 client secret
 *   GOOGLE_OAUTH_REDIRECT_URI   – Redirect URI registered in Google Cloud
 *                                  Console, e.g.:
 *                                  dev:  http://localhost:5000/api/auth/callback
 *                                  prod: https://your-app.onrender.com/api/auth/callback
 */

import { OAuth2Client } from 'google-auth-library';

function getRequiredEnv(name) {
  const value = process.env[name]?.trim();
  if (!value) {
    throw new Error(`Missing required environment variable: ${name}`);
  }
  return value;
}

function getOptionalEnv(name) {
  return process.env[name]?.trim() || '';
}

/**
 * Returns a configured OAuth2Client instance.
 */
function getOAuthClient() {
  return new OAuth2Client(
    getRequiredEnv('GOOGLE_OAUTH_CLIENT_ID'),
    getRequiredEnv('GOOGLE_OAUTH_CLIENT_SECRET'),
    getRequiredEnv('GOOGLE_OAUTH_REDIRECT_URI'),
  );
}

/**
 * Builds the Google authorization URL. The `state` value is a random
 * nonce stored in the session before the redirect; it is validated on
 * the callback to prevent CSRF.
 *
 * @param {string} state  Random nonce generated by the caller.
 * @returns {string}      Full authorization URL.
 */
export function getAuthorizationUrl(state) {
  const client = getOAuthClient();
  const hostedDomain = getOptionalEnv('GOOGLE_OAUTH_HOSTED_DOMAIN').toLowerCase();
  const authUrlOptions = {
    access_type: 'online',
    scope: ['openid', 'email', 'profile'],
    prompt: 'select_account',
    state,
  };

  if (hostedDomain) {
    authUrlOptions.hd = hostedDomain;
  }

  return client.generateAuthUrl(authUrlOptions);
}

/**
 * Exchanges an authorization code for tokens, verifies the ID token, and
 * returns the verified token payload (contains `email`, `name`, `picture`
 * among other standard OIDC claims).
 *
 * Throws if the code exchange or token verification fails.
 *
 * @param {string} code  Authorization code from Google callback.
 * @returns {Promise<import('google-auth-library').TokenPayload>}
 */
export async function verifyGoogleCode(code) {
  const client = getOAuthClient();
  const { tokens } = await client.getToken(code);

  if (!tokens.id_token) {
    throw new Error('Google OAuth response did not include an ID token.');
  }

  const ticket = await client.verifyIdToken({
    idToken: tokens.id_token,
    audience: getRequiredEnv('GOOGLE_OAUTH_CLIENT_ID'),
  });
  return ticket.getPayload();
}
